#
# This is an initial SwiftLint configuration for the hemnet-ios project
#
# All disabled rules are rules that was violated when the configuration
# was added. Moving forward we can opt to remove one rule at a time to
# fix the issues in a structured way.
#
# We can also reverse this by opting into the rules we really care about,
# but it is probably better to adapt the community 'best practice' rules
# from SwiftLint defaults.
#

only_rules:
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - colon
  - comma
#  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - control_statement
#  - custom_rules
#  - cyclomatic_complexity
  - deployment_target
  - discouraged_direct_init
  - duplicate_enum_cases
  - duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
#  - file_length
  - for_where
#  - force_cast
#  - force_try
#  - function_body_length
#  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - implicit_return
#  - inclusive_language
#  - inert_defer
  - is_disjoint
#  - large_tuple
  - leading_whitespace
#  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_random
#  - line_length
#  - mark
#  - multiple_closures_with_trailing_closure
#  - nesting
#  - no_fallthrough_only
  - no_space_in_method_call
#  - notification_center_detachment
#  - ns_number_init_as_function_reference
#  - nsobject_prefer_isequal
  - opening_brace
  - operator_whitespace
#  - orphaned_doc_comment
#  - private_over_fileprivate
#  - private_unit_test
#  - protocol_property_accessors_order
#  - reduce_boolean
#  - redundant_discardable_let
#  - redundant_objc_attribute
#  - redundant_optional_initialization
#  - redundant_set_access_control
#  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
#  - self_in_property_initialization
#  - shorthand_operator
#  - statement_position
#  - superfluous_disable_command
  - switch_case_alignment
#  - syntactic_sugar
#  - todo
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
#  - trailing_whitespace
#  - type_body_length
#  - type_name
#  - unavailable_condition
#  - unneeded_break_in_switch
#  - unused_capture_list
#  - unused_closure_parameter
#  - unused_control_flow_label
#  - unused_enumerated
#  - unused_optional_binding
#  - unused_setter_value
#  - valid_ibinspectable
#  - vertical_parameter_alignment
  - vertical_whitespace
#  - void_function_in_ternary
  - void_return
  - xctfail_message
  - xct_specific_matcher # optional rule
excluded:
  - Carthage
  - Vendor
  - mint

trailing_comma:
  mandatory_comma: true

deployment_target:
  iOS_deployment_target: 14.0

colon:
  flexible_right_spacing: true

identifier_name:
  excluded:
    - _body(configuration:)
  min_length: 1
  max_length: 60

