---
format_version: "11"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios

meta:
  bitrise.io:
    stack: osx-xcode-15.0.x
    machine_type_id: g2-m1.4core

app:
  envs:
    - BITRISE_PROJECT_PATH: Testy.xcodeproj
    - BITRISE_SCHEME: Testy
    - BITRISE_PACKAGE_TEST_SCHEME: MyLibraryTests
    - BITRISE_DISTRIBUTION_METHOD: development

pipelines:
  # Pipeline
  test:
    stages:
    - run_tests: {}
    - upload_testflight: {}
  # Pipeline using environment variables
  test_variables:
    stages:
    - run_tests_variables: {}
    - upload_testflight: {}

stages:
  # Stage using separate workflows
  run_tests:
    workflows:
    - run_tests_default_locale: {}
    - run_tests_swedish_locale: {}
  # Stage using environment variables
  run_tests_variables:
    workflows:
    - run_tests: {}
    - run_tests:
        envs:
        - ENV_LANGUAGE: sv
        - ENV_REGION: SE
  upload_testflight:
    workflows:
    - upload_testflight: {}

workflows:
  # This workflow runs the tests using system language and region
  run_tests_default_locale:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@6.1.1: {}
    - install-bundler: {}
    - script@1.1.6:
        title: Validate SwiftLint plugin
        inputs:
        - content: |-
            #!/usr/bin/env bash

            mkdir -p ~/Library/org.swift.swiftpm/security
            cp -r ./.swiftplugin/security/ ~/Library/org.swift.swiftpm/security
    - script@1.1.6:
        title: Generate project and run tests
        inputs:
        - content: |-
            #!/usr/bin/env bash

            xcodegen generate
            bundle exec fastlane tests

  # This workflow runs the tests using Swedish language and region
  run_tests_swedish_locale:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@6.1.1: {}
    - install-bundler: {}
    - script@1.1.6:
        title: Validate SwiftLint plugin
        inputs:
        - content: |-
            #!/usr/bin/env bash

            mkdir -p ~/Library/org.swift.swiftpm/security
            cp -r ./.swiftplugin/security/ ~/Library/org.swift.swiftpm/security
    - script@1.1.6:
        title: Generate project and run tests
        inputs:
        - content: |-
            #!/usr/bin/env bash

            xcodegen generate
            bundle exec fastlane tests test_language:sv test_region:SE

  # This workflow runs the tests using language and region from environment variable
  run_tests:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@6.1.1: {}
    - install-bundler: {}
    - script@1.1.6:
        title: Validate SwiftLint plugin
        inputs:
        - content: |-
            #!/usr/bin/env bash

            mkdir -p ~/Library/org.swift.swiftpm/security
            cp -r ./.swiftplugin/security/ ~/Library/org.swift.swiftpm/security
    - script@1.1.6:
        title: Generate project and run tests
        inputs:
        - content: |-
            #!/usr/bin/env bash

            xcodegen generate
            bundle exec fastlane tests test_language:$ENV_LANGUAGE test_region:$ENV_REGION

  upload_testflight:
    summary: Fakes an upload to TestFlight.
    description: This workflow will just echo some text by running a script.
    steps:
      - script@1:
          inputs:
          - content: |-
              #!/usr/bin/env bash

              echo "Upload to TestFlight"


trigger_map:
  - push_branch: main
    pipeline: test
