---
format_version: "11"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios

meta:
  bitrise.io:
    stack: osx-xcode-15.0.x
    machine_type_id: g2-m1.4core

app:
  envs:
    - BITRISE_PROJECT_PATH: Testy.xcodeproj
    - BITRISE_SCHEME: Testy
    - BITRISE_PACKAGE_TEST_SCHEME: MyLibraryTests
    - BITRISE_DISTRIBUTION_METHOD: development

pipelines:
  # Pipeline using environment variables
  test:
    stages:
    - build_tests: {}
    - run_tests: {}
    - upload_testflight: {}

stages:
  # Build stage only for testing
  build_tests:
    title: Build for testing
    workflows:
    - build_for_testing: {}
  # Test stage using environment variables
  run_tests:
    title: Stage with variables
    abort_on_fail: true
    workflows:
    - run_tests_default_locale: {}
    - run_tests_swedish_locale: {}
  upload_testflight:
    workflows:
    - upload_testflight: {}

workflows:
  # This workflow compiles the project for testing
  build_for_testing:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@6.1.1: {}
    - install-bundler: {}
    - script@1.1.6:
        title: Validate SwiftLint plugin
        inputs:
        - content: |-
            #!/usr/bin/env bash

            mkdir -p ~/Library/org.swift.swiftpm/security
            cp -r ./.swiftplugin/security/ ~/Library/org.swift.swiftpm/security
    - script@1.1.6:
        title: Build for testing
        inputs:
        - content: |-
            #!/usr/bin/env bash

            bundle exec fastlane build_for_testing
    - deploy-to-bitrise-io@2:
        inputs:
        - pipeline_intermediate_files: |-
            $BITRISE_SOURCE_DIR/Gemfile:BITRISE_GEMFILE_PATH
            $BITRISE_SOURCE_DIR/Gemfile.lock:BITRISE_GEMFILE_LOCK_PATH
            $BITRISE_SOURCE_DIR/.ruby-version:BITRISE_RUBY_VERSION_PATH
            $BITRISE_DEPLOY_DIR:BITRISE_DEPLOY_DIR

  # This workflow runs the tests using system language and region
  run_tests_default_locale:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - pull-intermediate-files@1:
        inputs:
        - artifact_sources: 'build_tests.build_for_testing'
    - install-bundler:
        inputs:
        - gemfile_path: '$BITRISE_GEMFILE_PATH'
        - gemfilelock_dir: '$BITRISE_GEMFILE_LOCK_PATH'
    - script@1.1.6:
        title: Run tests with system language and region
        inputs:
        - content: |-
            #!/usr/bin/env bash

            bundle exec fastlane tests

  # This workflow runs the tests using Swedish language and region
  run_tests_swedish_locale:
    envs:
      - ENV_LANGUAGE: sv
      - ENV_REGION: SE
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - pull-intermediate-files@1:
        inputs:
        - artifact_sources: 'build_tests.build_for_testing'
    - install-bundler:
        inputs:
        - gemfile_path: '$BITRISE_GEMFILE_PATH'
        - gemfilelock_dir: '$BITRISE_GEMFILE_LOCK_PATH'
    - script@1.1.6:
        title: Run tests with Swedish language and region
        inputs:
        - content: |-
            #!/usr/bin/env bash
            bundle exec fastlane tests test_language:$ENV_LANGUAGE test_region:$ENV_REGION

  upload_testflight:
    summary: Fakes an upload to TestFlight.
    description: This workflow will just echo some text by running a script.
    steps:
      - script@1:
          inputs:
          - content: |-
              #!/usr/bin/env bash

              echo "Upload to TestFlight"

trigger_map:
  - push_branch: main
    pipeline: test
