name: Testy
options:
  bundleIdPrefix: se.marber
  deploymentTarget:
    iOS: "16.4"
targets:
  Testy:
    type: application
    platform: iOS
    sources:
      - path: Testy/
        name: Testy
    settings:
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      GENERATE_INFOPLIST_FILE: YES
    scheme:
      testTargets:
        - name: TestyTests

  TestyTests:
    type: bundle.unit-test
    settings:
      GENERATE_INFOPLIST_FILE: YES
    platform: iOS
    sources:
      - TestyTests/

packages:
  SwiftLint:
    url: https://github.com/realm/SwiftLint.git
    exactVersion: 0.52.4

  MyLibrary:
    path: ./MyLibrary