# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

project = "Testy.xcodeproj"

platform :ios do
  lane :tests do |options|
    test_language = options[:test_language]
    test_region = options[:test_region]

    xcargs = nil
    if !test_language.to_s.empty? && !test_region.to_s.empty?
      xcargs = "-testLanguage #{test_language} -testRegion #{test_region}"
    end

    scan(
      project: project,
      scheme: 'Testy',
      reset_simulator: true,
      devices: ['iPhone 13'],
      disable_concurrent_testing: true,
      code_coverage: false,
      output_types: 'junit',
      output_directory: ENV['BITRISE_DEPLOY_DIR'],
      output_files: 'report.xml',
      xcargs: xcargs,
      skip_build: true,
      result_bundle: false,
      should_zip_build_products: false,
      suppress_xcode_output: false
    )
  end
end
