name: CI

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'testflight' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Trigger a build in Bitrise and upload to TestFlight
      env:
        BITRISE_ACCESS_TOKEN: ${{ secrets.BITRISE_ACCESS_TOKEN }}
        BITRISE_APP_SLUG: ${{ secrets.BITRISE_APP_SLUG }}
        BITRISE_TRIGGER_TOKEN: ${{ secrets.BITRISE_TRIGGER_TOKEN }}
      run: |
        curl -H 'Authorization: $BITRISE_ACCESS_TOKEN' \
             https://app.bitrise.io/app/$BITRISE_APP_SLUG/build/start.json -L \
             --data '{
              "build_params": {
                "branch": "main",
                "workflow_id": "upload_testflight"
              },
              "hook_info": {
                "build_trigger_token": "$BITRISE_TRIGGER_TOKEN",
                "type": "bitrise"
              }
             }'